name: Generate Documentation

on:
  schedule:
    - cron: '0 0 * * *'  # Corre diariamente
  workflow_dispatch:      # Permite ejecutar manualmente
  issues:
    types: [opened, closed, edited, deleted]
  milestone:
    types: [created, closed, edited, deleted]

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub markdown2 jinja2

      - name: Fetch Issues and Milestones
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python scripts/fetch_github_data.py

      - name: Generate Documentation
        run: |
          python scripts/generate_docs.py

      - name: Commit and Push if changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update documentation [skip ci]" && git push) 